@echo off
echo Cleaning up existing processes on port 8000...
for /f "tokens=5" %%a in ('netstat -ano ^| findstr :8000 ^| findstr LISTENING') do taskkill /F /PID %%a 2>nul
echo Starting BicheWare Server...
echo Opening http://localhost:8000 in your browser...
start "" http://localhost:8000
python -m http.server 8000
pause
